# Generated by Django 4.2.11 on 2024-04-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="token_ws",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
