# Generated by Django 4.2.11 on 2024-04-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_categoria_producto_pedido_itempedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("en_carrito", "En Carrito"),
                    ("pendiente", "Pendiente"),
                    ("procesando", "Procesando"),
                    ("enviado", "Enviado"),
                    ("entregado", "Entregado"),
                    ("cancelado", "Cancelado"),
                ],
                default="en_carrito",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
