# Generated by Django 4.2.11 on 2024-04-19 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_carrito"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itempedido",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="item_pedidos",
                to="backend.producto",
            ),
        ),
    ]
