# Generated by Django 4.2.11 on 2024-04-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_itempedido_producto"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCarrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                ("cantidad", models.IntegerField(default=1, verbose_name="Cantidad")),
                (
                    "carrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="backend.carrito",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_carritos",
                        to="backend.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Carrito",
                "verbose_name_plural": "Items de Carrito",
            },
        ),
        migrations.AddField(
            model_name="carrito",
            name="productos",
            field=models.ManyToManyField(
                through="backend.ItemCarrito", to="backend.producto"
            ),
        ),
    ]
