# Generated by Django 4.2.11 on 2024-04-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_itemcarrito_carrito_productos"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="comuna",
            field=models.CharField(blank=True, max_length=50, verbose_name="Comuna"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Dirección"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="region",
            field=models.CharField(blank=True, max_length=50, verbose_name="Región"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefono",
            field=models.CharField(blank=True, max_length=12, verbose_name="Telefono"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nombre",
            field=models.CharField(max_length=200, verbose_name="Nombre"),
        ),
    ]
